/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.Calendar;
import java.util.GregorianCalendar;
import negocio.CityTour;
import negocio.Ciudad;
import negocio.Cliente;
import negocio.Habitacion;
import negocio.Hotel;
import negocio.Paquete;
import negocio.PlanAlimentacionHotel;
import negocio.Vuelo;

/**
 *
 * @author brayangarcia
 */
public class GUIFactura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    Paquete myPaquete;
    Cliente myCliente;
    int monto;
    int indiceTabla;
   String [][] vecTabla= new String[30][3];

    public GUIFactura(Paquete myPaquete,Cliente myCliente,int monto) {
        initComponents();
        this.myPaquete= myPaquete;
        this.myCliente=myCliente;
        indiceTabla=0;
        this.monto= monto;
       generarFactura();
        fixTableFactura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtIdCliente = new javax.swing.JTextField();
        TxtNombresCliente = new javax.swing.JTextField();
        TxtApellidosCliente = new javax.swing.JTextField();
        TxtFechaCompra = new javax.swing.JTextField();
        TxtIdPaquete = new javax.swing.JTextField();
        TxtCostoTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtMontoPagado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtFormaDePago = new javax.swing.JTextField();
        JSPFactura = new javax.swing.JScrollPane();
        TblFactura = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id Cliente");

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Fecha de Compra");

        jLabel5.setText("Id paquete");

        jLabel6.setText("Forma de pago");

        TxtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdClienteActionPerformed(evt);
            }
        });

        TxtCostoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCostoTotalActionPerformed(evt);
            }
        });

        jLabel8.setText("Costo Total");

        jLabel9.setText("Monto Pagado");

        TblFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo Articulo", "Descripcion", "Precio"
            }
        ));
        JSPFactura.setViewportView(TblFactura);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNombresCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtApellidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFormaDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtMontoPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtIdPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(TxtFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(JSPFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(TxtFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(TxtNombresCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtIdPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtApellidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(TxtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtFormaDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TxtMontoPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(JSPFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCostoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCostoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCostoTotalActionPerformed

    private void TxtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdClienteActionPerformed
    public void generarFactura(){
        Calendar fecha = new GregorianCalendar();
        //Obtenemos el valor del año, mes, día,
        //hora, minuto y segundo del sistema
        //usando el método get y el parámetro correspondiente
        int myAnio = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH)+1;
        int dia = fecha.get(Calendar.DAY_OF_MONTH);

        String myDia=convertirDiaoMesAHsqldb(dia);
        String myMes=convertirDiaoMesAHsqldb(mes);
        String fechaCompra = myAnio+"-"+myMes+"-"+myDia;

        TxtIdCliente.setText(String.valueOf(myCliente.getIdentificacion()));
        TxtNombresCliente.setText(myCliente.getNombres());
        TxtApellidosCliente.setText(myCliente.getApellidos());
        TxtCostoTotal.setText(String.valueOf(myPaquete.getPrecio()));
        TxtFechaCompra.setText(fechaCompra);
        TxtIdPaquete.setText(String.valueOf(myPaquete.getIdPaquete()));
        TxtMontoPagado.setText(String.valueOf(monto));
        inicializarTablaHoteles();
        inicializarTablaVuelos();
       inicializarTablaCityTours();
        inicializarTablaPlanesAlimentacion();


    }

    private String convertirDiaoMesAHsqldb(int diaoMes) {
          String conversion=String.valueOf(diaoMes);
        if(diaoMes<10){
            conversion="0"+diaoMes;
        }
        return conversion;
    }

    public void inicializarTablaHoteles(){
        for (int i = 0; i < myPaquete.getComponentes().size(); i++) {
            Ciudad myCiudad =  (Ciudad) myPaquete.getComponentes().get(i);

            for (int j = 0; j < myCiudad.getComponentes().size(); j++) {
                if(myCiudad.getComponentes().get(j) instanceof Hotel){

                    Hotel myHotel = (Hotel)myCiudad.getComponentes().get(j);

                    for (int k = 0; k < myHotel.getArrayComponentes().size(); k++) {

                        if( myHotel.getArrayComponentes().get(k) instanceof Habitacion){

                            Habitacion myHabitacion = (Habitacion) myHotel.getArrayComponentes().get(k);
                            vecTabla[indiceTabla][0]="Hotel";
                            vecTabla[indiceTabla][1]="Nombre Hotel: "+myHotel.getNombreHotel()+" Numero Habitacion: "+myHabitacion.getNumeroHabitacion()
                                    +" Descripcion: "+myHabitacion.getDescripcion();
                            vecTabla[indiceTabla][2]="$"+myHabitacion.getPrecio();
                            indiceTabla+=1;

                        }
                    }
                }
            }
        }
        String [] columnIdentifiers = {"Tipo Articulo","Descripcion","Precio"};
        TblFactura.setModel(new javax.swing.table.DefaultTableModel(
                vecTabla,columnIdentifiers));

    }

    public void fixTableFactura(){
         TblFactura.getColumnModel().getColumn(0).setPreferredWidth(20);
        TblFactura.getColumnModel().getColumn(1).setPreferredWidth(450);
         TblFactura.getColumnModel().getColumn(2).setPreferredWidth(30);

    }
    public void inicializarTablaVuelos(){

        for (int i = 0; i < myPaquete.getComponentes().size(); i++) {
            Ciudad myCiudad = (Ciudad) myPaquete.getComponentes().get(i);

            for (int j = 0; j < myCiudad.getComponentes().size(); j++) {

                if(myCiudad.getComponentes().get(j) instanceof Vuelo){

                        Vuelo myVuelo = (Vuelo)myCiudad.getComponentes().get(j);

                        vecTabla[indiceTabla][0]="Vuelo";
                        vecTabla[indiceTabla][1]=
                                  "Id vuelo: "+String.valueOf(myVuelo.getIdVuelo())
                                  +" aerolinea: "+myVuelo.getAerolinea()
                                  +" Ciudad origen: "+myVuelo.getNombreCiudadOrigen()
                                  +" Ciudad destino: "+myVuelo.getNombreCiudadDestino()
                                  +" fecha salida: "+myVuelo.getFechaHoraSalida()
                                  + " fechaLlegada: "+myVuelo.getFechaHoraLlegada();
                        vecTabla[indiceTabla][2]=String.valueOf(myVuelo.getPrecio());
                        indiceTabla+=1;

                    }
                }
            }
         String [] columnIdentifiers = {"Tipo Articulo","Descripcion","Precio"};
        TblFactura.setModel(new javax.swing.table.DefaultTableModel(
                vecTabla,columnIdentifiers));

     }
     public void inicializarTablaCityTours(){

        for (int i = 0; i < myPaquete.getComponentes().size(); i++) {
            Ciudad myCiudad = (Ciudad) myPaquete.getComponentes().get(i);

            for (int j = 0; j < myCiudad.getComponentes().size(); j++) {

                if(myCiudad.getComponentes().get(j) instanceof CityTour){

                        CityTour myCityTour = (CityTour)myCiudad.getComponentes().get(j);
                        vecTabla[indiceTabla][0]="City Tour";
                        vecTabla[indiceTabla][1]=
                                " id CityTour: "+String.valueOf(myCityTour.getIdCityTour())
                                +" Ciudad: "+myCiudad.getNombreCiudad()
                                +" descripcion: "+myCityTour.getDescripcion()
                                +" Fecha Inicio: "+myCityTour.getFechaInicio()
                                +" Fecha Fin: "+myCityTour.getFechaFin();
                        vecTabla[indiceTabla][2]=String.valueOf(myCityTour.getPrecio());
                        indiceTabla+=1;


                    }
                }
            }
        String [] columnIdentifiers = {"Tipo Articulo","Descripcion","Precio"};
        TblFactura.setModel(new javax.swing.table.DefaultTableModel(
                vecTabla,columnIdentifiers));

     }


    public void inicializarTablaPlanesAlimentacion(){


        for (int i = 0; i < myPaquete.getComponentes().size(); i++) {
            Ciudad myCiudad = (Ciudad) myPaquete.getComponentes().get(i);

            for (int j = 0; j < myCiudad.getComponentes().size(); j++) {
                if(myCiudad.getComponentes().get(j) instanceof Hotel){

                    Hotel myHotel = (Hotel)myCiudad.getComponentes().get(j);

                    for (int k = 0; k < myHotel.getArrayComponentes().size(); k++) {

                        if( myHotel.getArrayComponentes().get(k) instanceof PlanAlimentacionHotel){

                            PlanAlimentacionHotel myPlanAli = (PlanAlimentacionHotel) myHotel.getArrayComponentes().get(k);
                            vecTabla[indiceTabla][0]="Plan de alimentacion";
                            vecTabla[indiceTabla][1]=
                                    "Id: "+String.valueOf(myPlanAli.getIdPlanAlimentacion())
                                    +" Hotel: "+myHotel.getNombreHotel()
                                    +" Ciudad: "+myCiudad.getNombreCiudad()
                                    +" Descripcion: "+myPlanAli.getDescripcion();
                            vecTabla[indiceTabla][2]=String.valueOf(myPlanAli.getPrecio());

                            indiceTabla+=1;
                        }
                    }
                }
            }
        }
        String [] columnIdentifiers = {"Tipo Articulo","Descripcion","Precio"};
        TblFactura.setModel(new javax.swing.table.DefaultTableModel(
                vecTabla,columnIdentifiers));



     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFactura(new Paquete(), new Cliente(),0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JSPFactura;
    private javax.swing.JTable TblFactura;
    private javax.swing.JTextField TxtApellidosCliente;
    private javax.swing.JTextField TxtCostoTotal;
    private javax.swing.JTextField TxtFechaCompra;
    private javax.swing.JTextField TxtFormaDePago;
    private javax.swing.JTextField TxtIdCliente;
    private javax.swing.JTextField TxtIdPaquete;
    private javax.swing.JTextField TxtMontoPagado;
    private javax.swing.JTextField TxtNombresCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
