package presentacion;

import negocio.Administrador;
import negocio.Funcionario;

import recursos.Utilidades;

import java.io.IOException;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import negocio.VentanaDisponible;

/**
 *
 * @author danielmej
 */
public class GUIGestionUsuarios extends javax.swing.JInternalFrame {
    
    Administrador administrador;
;
    private static GUIGestionUsuarios ventana =null;
     private static VentanaDisponible myUnicaVentana;
    /**
     * Creates new form GUIGestorUsuarios
     */
    public GUIGestionUsuarios(Administrador administrador, VentanaDisponible myUnicaVentana ) {
        this.administrador=administrador;
        initComponents();
        //setIconImage(new ImageIcon(getClass().getResource("/recursos/clothing.png")).getImage());
        btnGroupCargoAU.add(rbtnAdministradorAU);
        btnGroupCargoAU.add(rbtnFuncionarioAU);
        
        btnGroupCargoUU.add(rbtnAdministradorUU);
        btnGroupCargoUU.add(rbtnFuncionarioUU);
        this.myUnicaVentana = myUnicaVentana;
    }
    
    public static GUIGestionUsuarios GUIGestionUsuarios(Administrador admin,VentanaDisponible myUnicaVentana){
        if(myUnicaVentana.isNuevaVentana()){
            ventana=new GUIGestionUsuarios(admin, new VentanaDisponible());
            GUIGestionUsuarios.myUnicaVentana = myUnicaVentana;
            
        }
        return ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCargoAU = new javax.swing.ButtonGroup();
        btnGroupCargoUU = new javax.swing.ButtonGroup();
        pnlGestionUsuarios = new javax.swing.JPanel();
        lblGestionUsuarios = new javax.swing.JLabel();
        lblImagenDataBase = new javax.swing.JLabel();
        lblImgGestionUsuarios = new javax.swing.JLabel();
        pnlsGestionUsuario = new javax.swing.JTabbedPane();
        pnlAgregarUsuario = new javax.swing.JPanel();
        lblCargoAU = new javax.swing.JLabel();
        btnComprobarAU = new javax.swing.JButton();
        lblNombreAU = new javax.swing.JLabel();
        lblNombreCompletoAU = new javax.swing.JLabel();
        lblContraseniaAU = new javax.swing.JLabel();
        txtNombreCompletoAU = new javax.swing.JTextField();
        txtContraseniaAU = new javax.swing.JTextField();
        lblInfo2AU = new javax.swing.JLabel();
        btnAgregarUsuario = new javax.swing.JButton();
        lblInfoAC = new javax.swing.JLabel();
        txtNombreAU = new javax.swing.JTextField();
        rbtnAdministradorAU = new javax.swing.JRadioButton();
        rbtnFuncionarioAU = new javax.swing.JRadioButton();
        pnlActualizarUsuario = new javax.swing.JPanel();
        btnBuscarUU = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        txtContraseniaUU = new javax.swing.JTextField();
        lblNombreCompletoUU = new javax.swing.JLabel();
        txtNombreUU = new javax.swing.JTextField();
        lblInfoUU = new javax.swing.JLabel();
        lblContraseniaUU = new javax.swing.JLabel();
        rbtnFuncionarioUU = new javax.swing.JRadioButton();
        lblNombreUU = new javax.swing.JLabel();
        rbtnAdministradorUU = new javax.swing.JRadioButton();
        txtNombreCompletoUU = new javax.swing.JTextField();
        lblCargoUU = new javax.swing.JLabel();
        pnlConsultarUsuario = new javax.swing.JPanel();
        lblNombreCU = new javax.swing.JLabel();
        lblContraseniaCU = new javax.swing.JLabel();
        lblNombreCompletoCU = new javax.swing.JLabel();
        lblGeneroCU = new javax.swing.JLabel();
        lblCargoCU = new javax.swing.JLabel();
        txtNombreCompletoCU = new javax.swing.JTextField();
        txtContraseniaCU = new javax.swing.JTextField();
        txtCargoCU = new javax.swing.JTextField();
        txtFechaCU = new javax.swing.JTextField();
        btnBuscarUsuario = new javax.swing.JButton();
        txtNombreCU = new javax.swing.JTextField();
        pnlEliminarUsuario = new javax.swing.JPanel();
        lblNombreEU = new javax.swing.JLabel();
        btnEliminarUsuario = new javax.swing.JButton();
        txtNombreEU = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Usuarios");

        pnlGestionUsuarios.setBackground(new java.awt.Color(19, 64, 116));

        lblGestionUsuarios.setFont(new java.awt.Font("Quicksand", 1, 22)); // NOI18N
        lblGestionUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionUsuarios.setText("Gestion Usuarios");

        lblImagenDataBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/boss-1.png"))); // NOI18N

        lblImgGestionUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/database-3.png"))); // NOI18N

        pnlsGestionUsuario.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        pnlsGestionUsuario.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        pnlsGestionUsuario.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                pnlsGestionUsuarioComponentRemoved(evt);
            }
        });

        pnlAgregarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlAgregarUsuario.setForeground(new java.awt.Color(230, 232, 230));

        lblCargoAU.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblCargoAU.setText("Cargo * :");

        btnComprobarAU.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        btnComprobarAU.setText("Comprobar");
        btnComprobarAU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnComprobarAU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComprobarAU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarAUActionPerformed(evt);
            }
        });

        lblNombreAU.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        lblNombreAU.setText("Nombre * :");

        lblNombreCompletoAU.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblNombreCompletoAU.setText("Nombre Completo * :");

        lblContraseniaAU.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblContraseniaAU.setText("Contraseña * : ");
        lblContraseniaAU.setToolTipText("");

        txtNombreCompletoAU.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N

        txtContraseniaAU.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N

        lblInfo2AU.setFont(new java.awt.Font("Quicksand", 2, 12)); // NOI18N
        lblInfo2AU.setText("Puede verificar si un usuario existe con el boton \"Comprobar\"");

        btnAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/save.png"))); // NOI18N
        btnAgregarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });

        lblInfoAC.setFont(new java.awt.Font("Quicksand", 2, 12)); // NOI18N
        lblInfoAC.setText("Los campos seguidos de * son obligatorios");

        txtNombreAU.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N

        rbtnAdministradorAU.setBackground(new java.awt.Color(255, 255, 255));
        rbtnAdministradorAU.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        rbtnAdministradorAU.setText("Administrador");

        rbtnFuncionarioAU.setBackground(new java.awt.Color(255, 255, 255));
        rbtnFuncionarioAU.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        rbtnFuncionarioAU.setText("Funcionario");

        javax.swing.GroupLayout pnlAgregarUsuarioLayout = new javax.swing.GroupLayout(pnlAgregarUsuario);
        pnlAgregarUsuario.setLayout(pnlAgregarUsuarioLayout);
        pnlAgregarUsuarioLayout.setHorizontalGroup(
            pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarUsuarioLayout.createSequentialGroup()
                .addGroup(pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarUsuarioLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfo2AU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInfoAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlAgregarUsuarioLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreAU)
                            .addComponent(lblNombreCompletoAU)
                            .addComponent(lblContraseniaAU)
                            .addComponent(lblCargoAU))
                        .addGap(40, 40, 40)
                        .addGroup(pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAgregarUsuarioLayout.createSequentialGroup()
                                .addComponent(rbtnFuncionarioAU)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlAgregarUsuarioLayout.createSequentialGroup()
                                .addGroup(pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtContraseniaAU, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(txtNombreCompletoAU)
                                    .addComponent(rbtnAdministradorAU)
                                    .addComponent(txtNombreAU))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnComprobarAU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarUsuarioLayout.createSequentialGroup()
                                        .addComponent(btnAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)))))))
                .addContainerGap())
        );
        pnlAgregarUsuarioLayout.setVerticalGroup(
            pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarUsuarioLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblInfoAC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnComprobarAU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addComponent(btnAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAgregarUsuarioLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContraseniaAU, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAgregarUsuarioLayout.createSequentialGroup()
                                .addComponent(lblNombreAU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lblContraseniaAU)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreCompletoAU, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreCompletoAU))
                        .addGroup(pnlAgregarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAgregarUsuarioLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(rbtnAdministradorAU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnFuncionarioAU))
                            .addGroup(pnlAgregarUsuarioLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(lblCargoAU)))
                        .addGap(76, 76, 76)
                        .addComponent(lblInfo2AU)))
                .addGap(40, 40, 40))
        );

        pnlsGestionUsuario.addTab("Nuevo Usuario", pnlAgregarUsuario);

        pnlActualizarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlActualizarUsuario.setForeground(new java.awt.Color(230, 232, 230));

        btnBuscarUU.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        btnBuscarUU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/search.png"))); // NOI18N
        btnBuscarUU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarUU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarUU.setMaximumSize(new java.awt.Dimension(68, 68));
        btnBuscarUU.setMinimumSize(new java.awt.Dimension(68, 68));
        btnBuscarUU.setPreferredSize(new java.awt.Dimension(68, 68));
        btnBuscarUU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUUActionPerformed(evt);
            }
        });

        btnEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/save.png"))); // NOI18N
        btnEditarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });

        txtContraseniaUU.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N

        lblNombreCompletoUU.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblNombreCompletoUU.setText("Nombre Completo * :");

        txtNombreUU.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N

        lblInfoUU.setFont(new java.awt.Font("Quicksand", 2, 12)); // NOI18N
        lblInfoUU.setText("Los campos seguidos de * son obligatorios");

        lblContraseniaUU.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblContraseniaUU.setText("Contraseña * : ");
        lblContraseniaUU.setToolTipText("");

        rbtnFuncionarioUU.setBackground(new java.awt.Color(255, 255, 255));
        rbtnFuncionarioUU.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        rbtnFuncionarioUU.setText("Funcionario");

        lblNombreUU.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        lblNombreUU.setText("Nombre * :");

        rbtnAdministradorUU.setBackground(new java.awt.Color(255, 255, 255));
        rbtnAdministradorUU.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        rbtnAdministradorUU.setText("Administrador");

        txtNombreCompletoUU.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N

        lblCargoUU.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblCargoUU.setText("Cargo * :");

        javax.swing.GroupLayout pnlActualizarUsuarioLayout = new javax.swing.GroupLayout(pnlActualizarUsuario);
        pnlActualizarUsuario.setLayout(pnlActualizarUsuarioLayout);
        pnlActualizarUsuarioLayout.setHorizontalGroup(
            pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualizarUsuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addComponent(lblInfoUU, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)))
            .addGroup(pnlActualizarUsuarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualizarUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreUU)
                            .addComponent(lblContraseniaUU))
                        .addGap(81, 81, 81)
                        .addGroup(pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContraseniaUU, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreUU, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarUU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(pnlActualizarUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCompletoUU)
                            .addComponent(lblCargoUU))
                        .addGap(32, 32, 32)
                        .addGroup(pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnAdministradorUU)
                            .addComponent(txtNombreCompletoUU, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnFuncionarioUU))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlActualizarUsuarioLayout.setVerticalGroup(
            pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarUsuarioLayout.createSequentialGroup()
                .addGroup(pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualizarUsuarioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblInfoUU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarUU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlActualizarUsuarioLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreUU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreUU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseniaUU)
                    .addComponent(txtContraseniaUU, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCompletoUU)
                    .addComponent(txtNombreCompletoUU, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlActualizarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargoUU)
                    .addComponent(rbtnAdministradorUU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnFuncionarioUU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pnlsGestionUsuario.addTab("Actualizar Usuario", pnlActualizarUsuario);

        pnlConsultarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlConsultarUsuario.setForeground(new java.awt.Color(230, 232, 230));

        lblNombreCU.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        lblNombreCU.setText("Nombre:");

        lblContraseniaCU.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblContraseniaCU.setText("Contraseña");

        lblNombreCompletoCU.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblNombreCompletoCU.setText("Nombre Completo:");
        lblNombreCompletoCU.setToolTipText("");

        lblGeneroCU.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblGeneroCU.setText("Fecha de Creación:");

        lblCargoCU.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        lblCargoCU.setText("Cargo:");

        txtNombreCompletoCU.setEditable(false);
        txtNombreCompletoCU.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        txtNombreCompletoCU.setOpaque(false);

        txtContraseniaCU.setEditable(false);
        txtContraseniaCU.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        txtContraseniaCU.setOpaque(false);

        txtCargoCU.setEditable(false);
        txtCargoCU.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        txtCargoCU.setOpaque(false);

        txtFechaCU.setEditable(false);
        txtFechaCU.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        txtFechaCU.setOpaque(false);

        btnBuscarUsuario.setBackground(new java.awt.Color(51, 0, 255));
        btnBuscarUsuario.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        btnBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/search.png"))); // NOI18N
        btnBuscarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarUsuario.setMaximumSize(new java.awt.Dimension(68, 68));
        btnBuscarUsuario.setMinimumSize(new java.awt.Dimension(68, 68));
        btnBuscarUsuario.setPreferredSize(new java.awt.Dimension(68, 68));
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        txtNombreCU.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlConsultarUsuarioLayout = new javax.swing.GroupLayout(pnlConsultarUsuario);
        pnlConsultarUsuario.setLayout(pnlConsultarUsuarioLayout);
        pnlConsultarUsuarioLayout.setHorizontalGroup(
            pnlConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarUsuarioLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblNombreCU)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlConsultarUsuarioLayout.createSequentialGroup()
                .addGroup(pnlConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlConsultarUsuarioLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(pnlConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGeneroCU)
                            .addComponent(lblCargoCU)
                            .addComponent(lblContraseniaCU)
                            .addComponent(lblNombreCompletoCU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreCompletoCU, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtContraseniaCU)
                            .addComponent(txtCargoCU, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFechaCU, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(pnlConsultarUsuarioLayout.createSequentialGroup()
                        .addContainerGap(252, Short.MAX_VALUE)
                        .addComponent(txtNombreCU, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
        );
        pnlConsultarUsuarioLayout.setVerticalGroup(
            pnlConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultarUsuarioLayout.createSequentialGroup()
                .addGroup(pnlConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarUsuarioLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnlConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreCU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlConsultarUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(pnlConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContraseniaCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseniaCU))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCompletoCU)
                    .addComponent(txtNombreCompletoCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargoCU)
                    .addComponent(txtCargoCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGeneroCU)
                    .addComponent(txtFechaCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );

        pnlsGestionUsuario.addTab("Consultar Usuario", pnlConsultarUsuario);

        pnlEliminarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlEliminarUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlEliminarUsuario.setForeground(new java.awt.Color(230, 232, 230));

        lblNombreEU.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        lblNombreEU.setText("Nombre:");

        btnEliminarUsuario.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N
        btnEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/delete.png"))); // NOI18N
        btnEliminarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarUsuario.setMaximumSize(new java.awt.Dimension(68, 68));
        btnEliminarUsuario.setMinimumSize(new java.awt.Dimension(68, 68));
        btnEliminarUsuario.setPreferredSize(new java.awt.Dimension(68, 68));
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });

        txtNombreEU.setFont(new java.awt.Font("Quicksand", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlEliminarUsuarioLayout = new javax.swing.GroupLayout(pnlEliminarUsuario);
        pnlEliminarUsuario.setLayout(pnlEliminarUsuarioLayout);
        pnlEliminarUsuarioLayout.setHorizontalGroup(
            pnlEliminarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEliminarUsuarioLayout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(txtNombreEU, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(pnlEliminarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEliminarUsuarioLayout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(lblNombreEU)
                    .addContainerGap(495, Short.MAX_VALUE)))
        );
        pnlEliminarUsuarioLayout.setVerticalGroup(
            pnlEliminarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEliminarUsuarioLayout.createSequentialGroup()
                .addGroup(pnlEliminarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEliminarUsuarioLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEliminarUsuarioLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(txtNombreEU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(pnlEliminarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEliminarUsuarioLayout.createSequentialGroup()
                    .addGap(214, 214, 214)
                    .addComponent(lblNombreEU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(243, Short.MAX_VALUE)))
        );

        pnlsGestionUsuario.addTab("Eliminar Usuario", pnlEliminarUsuario);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGestionUsuariosLayout = new javax.swing.GroupLayout(pnlGestionUsuarios);
        pnlGestionUsuarios.setLayout(pnlGestionUsuariosLayout);
        pnlGestionUsuariosLayout.setHorizontalGroup(
            pnlGestionUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestionUsuariosLayout.createSequentialGroup()
                .addGroup(pnlGestionUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGestionUsuariosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnSalir)
                        .addGap(37, 37, 37)
                        .addComponent(lblImgGestionUsuarios)
                        .addGap(48, 48, 48)
                        .addComponent(lblGestionUsuarios)
                        .addGap(76, 76, 76)
                        .addComponent(lblImagenDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGestionUsuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlsGestionUsuario)))
                .addContainerGap())
        );
        pnlGestionUsuariosLayout.setVerticalGroup(
            pnlGestionUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestionUsuariosLayout.createSequentialGroup()
                .addGroup(pnlGestionUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgGestionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagenDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGestionUsuariosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblGestionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlGestionUsuariosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnSalir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlsGestionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGestionUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlGestionUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprobarAUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarAUActionPerformed
        Object usuarioConsulta=null;
        String v_nombre=" ";
        try{
            if(txtNombreAU.getText().length()==0){
                Utilidades.mensajeInformacion("Digite un nombre, por favor", "Informacion");
                return;
            }
            v_nombre=txtNombreAU.getText();
            usuarioConsulta = administrador.consultarUsuario(v_nombre);
            if(usuarioConsulta!=null){
                Utilidades.mensajeAdvertencia("El usuario ya esta registrado", "Advertencia");
            }else{
                Utilidades.mensajeExito("El nombre no esta en la base de datos", "Informacion");
            }
        }catch (IOException ex) {
            Logger.getLogger(Funcionario.class.getName()).log(Level.SEVERE, null, ex);
            Utilidades.mensajeAdvertencia("Se ha interrumpido la conexion con el servidor", "Error");
        }
    }//GEN-LAST:event_btnComprobarAUActionPerformed

    
    private boolean validarContraseniaUsuario(String contrasenia){
        return true;
    }
    
    private void limpiarCamposAgregarUsuario(){
        txtContraseniaAU.setText(" ");
        txtNombreCompletoAU.setText(" ");
        btnGroupCargoAU.clearSelection();
    }
    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        //Valido el nombre
        String v_nombre=" ";

        if(txtNombreAU.getText().length()==0){
                Utilidades.mensajeInformacion("Digite un nombre, por favor", "Informacion");
                return;
            }
        v_nombre=txtNombreAU.getText();        
        //Valido la contrasenia
        if(txtContraseniaAU.getText().length()==0){
            Utilidades.mensajeInformacion("Es obligatorio ingresar una contraseña", "Informacion");
            return;
        }
        if(!validarContraseniaUsuario(txtContraseniaAU.getText())){
            return;
        }
        String v_contrasenia=txtContraseniaAU.getText();
        //Valido nombre completo
        if(txtNombreCompletoAU.getText().length()==0){
            Utilidades.mensajeInformacion("Es obligatorio ingresar el nombre completo", "Informacion");
            return;
        }
        String v_nombreCompleto=txtNombreCompletoAU.getText();
        
        //Valido que se escogio un valor para el cargo
        int v_cargo=0;
        //10 = Administrador, 20=Funcionario
        if(rbtnAdministradorAU.isSelected()){
            v_cargo=10;
        }else if(rbtnFuncionarioAU.isSelected()){
            v_cargo=20;
        }else{
            Utilidades.mensajeInformacion("Escoga un cargo", "Informacion");
            return;
        }
        
        //Creo y agreggo un usuario dependiendo del cargo escogido (Administrador o funcionario)
        try{
            boolean agregado=false;
            if(v_cargo==10){
                Administrador nuevoUsuario=new Administrador(v_nombre, v_contrasenia, v_nombreCompleto, null);
                agregado = administrador.agregarUsuario(nuevoUsuario);

            }        
            if(v_cargo==20){
                Funcionario nuevoUsuario=new Funcionario(v_nombre, v_contrasenia, v_nombreCompleto, null);
                agregado = administrador.agregarUsuario(nuevoUsuario);
            }


            if(agregado){
                Utilidades.mensajeExito("Se agrego el Usuario", "Agregacion Exitosa");
                limpiarCamposAgregarUsuario();
            }else{
                Utilidades.mensajeError("El Usuario a agregar ya existe", "Error");
            }

        }catch (IOException ex) {
            Logger.getLogger(Funcionario.class.getName()).log(Level.SEVERE, null, ex);
            Utilidades.mensajeAdvertencia("Se ha interrumpido la conexion con el servidor", "Error");
        }
        
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void limpiarCamposBuscarUU(){
        txtContraseniaUU.setText(" ");
        txtNombreCompletoUU.setText(" ");
        btnGroupCargoUU.clearSelection();
        //txtFechaUU.setText(" ");
    }
    
    private void imprimirInfoUsuarioPnlEditar(Object usuario){
        if(usuario instanceof Administrador){
            rbtnAdministradorUU.setSelected(true);
            Administrador administradorConsultado =  (Administrador) usuario;
            txtContraseniaUU.setText(administradorConsultado.getContrasenia());
            txtNombreCompletoUU.setText(administradorConsultado.getNombreCompleto());
            //txtFechaCU.setText(administradorConsultado.getFechaCreacion());

        }
        
        if(usuario instanceof Funcionario){
            rbtnFuncionarioUU.setSelected(true);
            Funcionario funcionarioConsultado = (Funcionario) usuario;
            txtContraseniaUU.setText(funcionarioConsultado.getContrasenia());
            txtNombreCompletoUU.setText(funcionarioConsultado.getNombreCompleto());
            //txtFechaUU.setText(funcionarioConsultado.getFechaCreacion());
        }
    }
    private void btnBuscarUUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUUActionPerformed
        limpiarCamposBuscarUU();
        String v_nombre=" ";
        try{
            if(txtNombreUU.getText().length()==0){
                Utilidades.mensajeInformacion("Digite un nombre, por favor", "Informacion");
                return;
            }
            v_nombre=txtNombreUU.getText();
            
            Object usuarioConsulta = administrador.consultarUsuario(v_nombre);
            if(usuarioConsulta!=null){
                imprimirInfoUsuarioPnlEditar(usuarioConsulta);
            }else{
                Utilidades.mensajeError("El nombre ingresado no esta en la base de datos", "Error");
            }
        }catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
            Utilidades.mensajeAdvertencia("Se ha interrumpido la conexion con el servidor", "Error");
        }
        
        
    }//GEN-LAST:event_btnBuscarUUActionPerformed

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
        //Valido el nombre
        String v_nombre=" ";

        if(txtNombreUU.getText().length()==0){
                Utilidades.mensajeInformacion("Digite un nombre, por favor", "Informacion");
                return;
            }
        v_nombre=txtNombreUU.getText();        
        //Valido la contrasenia
        if(txtContraseniaUU.getText().length()==0){
            Utilidades.mensajeInformacion("Es obligatorio ingresar una contraseña", "Informacion");
            return;
        }
        if(!validarContraseniaUsuario(txtContraseniaUU.getText())){
            return;
        }
        String v_contrasenia=txtContraseniaUU.getText();
        //Valido nombre completo
        if(txtNombreCompletoUU.getText().length()==0){
            Utilidades.mensajeInformacion("Es obligatorio ingresar el nombre completo", "Informacion");
            return;
        }
        String v_nombreCompleto=txtNombreCompletoUU.getText();
        
        //Valido que se escogio un valor para el cargo
        int v_cargo=0;
        //10 = Administrador, 20=Funcionario
        if(rbtnAdministradorUU.isSelected()){
            v_cargo=10;
        }else if(rbtnFuncionarioUU.isSelected()){
            v_cargo=20;
        }else{
            Utilidades.mensajeInformacion("Escoga un cargo", "Informacion");
            return;
        }
        
        //Creo y agreggo un usuario dependiendo del cargo escogido (Administrador o funcionario)
        try{
            boolean editado=false;
            if(v_cargo==10){
                Administrador nuevoUsuario=new Administrador(v_nombre, v_contrasenia, v_nombreCompleto, null);
                editado = administrador.editarUsuario(nuevoUsuario);

            }        
            if(v_cargo==20){
                Funcionario nuevoUsuario=new Funcionario(v_nombre, v_contrasenia, v_nombreCompleto, null);
                editado = administrador.editarUsuario(nuevoUsuario);
            }


            if(editado){
                Utilidades.mensajeExito("Se edito el Usuario", "Actualizacion Exitosa");
                limpiarCamposAgregarUsuario();
            }else{
                Utilidades.mensajeError("El usuario a actualizar no existe", "Error");
            }

        }catch (IOException ex) {
            Logger.getLogger(Funcionario.class.getName()).log(Level.SEVERE, null, ex);
            Utilidades.mensajeAdvertencia("Se ha interrumpido la conexion con el servidor", "Error");
        }
        
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        String v_nombre=" ";
        try{          
            if(txtNombreEU.getText().length()==0){
                Utilidades.mensajeInformacion("Digite un nombre, por favor", "Informacion");
                return;
            }
            v_nombre=txtNombreEU.getText();
            int respuestaConfirmacion = JOptionPane.showConfirmDialog(null, "Esta seguro que desea realizar esta operacion", "Confirmacion", JOptionPane.YES_NO_OPTION,2, new ImageIcon("./src/Recursos/question.png"));
            boolean eliminado=false;
            if (respuestaConfirmacion == JOptionPane.YES_OPTION) {
                eliminado=administrador.eliminarUsuario(v_nombre);
            }
            else {
                return;
            }

            if(eliminado){
                Utilidades.mensajeExito("Se elimino el Usuario", "Borrado Exitoso");
            }else{
                Utilidades.mensajeError("El Usuario a eliminar no existe", "Error");
            }
        } catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
            Utilidades.mensajeAdvertencia("Se ha interrumpido la conexion con el servidor", "Error");
        }

    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void limpiarCamposBuscarUsuario(){
        txtContraseniaCU.setText(" ");
        txtNombreCompletoCU.setText(" ");
        txtCargoCU.setText(" ");
        txtFechaCU.setText(" ");
    }
    private void imprimirInfoUsuarioPnlConsultar(Object usuario){
        if(usuario instanceof Administrador){
            txtCargoCU.setText("Administrador");
            Administrador administradorConsultado =  (Administrador) usuario;
            txtContraseniaCU.setText(administradorConsultado.getContrasenia());
            txtNombreCompletoCU.setText(administradorConsultado.getNombreCompleto());
            txtFechaCU.setText(administradorConsultado.getFechaCreacion());

        }
        
        if(usuario instanceof Funcionario){
            txtCargoCU.setText("Funcionario");
            Funcionario funcionarioConsultado = (Funcionario) usuario;
            txtContraseniaCU.setText(funcionarioConsultado.getContrasenia());
            txtNombreCompletoCU.setText(funcionarioConsultado.getNombreCompleto());
            txtFechaCU.setText(funcionarioConsultado.getFechaCreacion());
        }
    }
    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        limpiarCamposBuscarUsuario();
        String v_nombre=" ";
        try{
            if(txtNombreCU.getText().length()==0){
                Utilidades.mensajeInformacion("Digite un nombre, por favor", "Informacion");
                return;
            }
            v_nombre=txtNombreCU.getText();
            
            Object usuarioConsulta = administrador.consultarUsuario(v_nombre);
            if(usuarioConsulta!=null){
                imprimirInfoUsuarioPnlConsultar(usuarioConsulta);
            }else{
                Utilidades.mensajeError("El nombre ingresado no esta en la base de datos", "Error");
            }
        }catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
            Utilidades.mensajeAdvertencia("Se ha interrumpido la conexion con el servidor", "Error");
        }
        
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void pnlsGestionUsuarioComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlsGestionUsuarioComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlsGestionUsuarioComponentRemoved

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        myUnicaVentana.setNuevaVentana(true);
        
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[],Administrador administrador) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIGestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIGestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIGestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIGestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIGestionUsuarios(administrador, new VentanaDisponible()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnBuscarUU;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnComprobarAU;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.ButtonGroup btnGroupCargoAU;
    private javax.swing.ButtonGroup btnGroupCargoUU;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblCargoAU;
    private javax.swing.JLabel lblCargoCU;
    private javax.swing.JLabel lblCargoUU;
    private javax.swing.JLabel lblContraseniaAU;
    private javax.swing.JLabel lblContraseniaCU;
    private javax.swing.JLabel lblContraseniaUU;
    private javax.swing.JLabel lblGeneroCU;
    private javax.swing.JLabel lblGestionUsuarios;
    private javax.swing.JLabel lblImagenDataBase;
    private javax.swing.JLabel lblImgGestionUsuarios;
    private javax.swing.JLabel lblInfo2AU;
    private javax.swing.JLabel lblInfoAC;
    private javax.swing.JLabel lblInfoUU;
    private javax.swing.JLabel lblNombreAU;
    private javax.swing.JLabel lblNombreCU;
    private javax.swing.JLabel lblNombreCompletoAU;
    private javax.swing.JLabel lblNombreCompletoCU;
    private javax.swing.JLabel lblNombreCompletoUU;
    private javax.swing.JLabel lblNombreEU;
    private javax.swing.JLabel lblNombreUU;
    private javax.swing.JPanel pnlActualizarUsuario;
    private javax.swing.JPanel pnlAgregarUsuario;
    private javax.swing.JPanel pnlConsultarUsuario;
    private javax.swing.JPanel pnlEliminarUsuario;
    private javax.swing.JPanel pnlGestionUsuarios;
    private javax.swing.JTabbedPane pnlsGestionUsuario;
    private javax.swing.JRadioButton rbtnAdministradorAU;
    private javax.swing.JRadioButton rbtnAdministradorUU;
    private javax.swing.JRadioButton rbtnFuncionarioAU;
    private javax.swing.JRadioButton rbtnFuncionarioUU;
    private javax.swing.JTextField txtCargoCU;
    private javax.swing.JTextField txtContraseniaAU;
    private javax.swing.JTextField txtContraseniaCU;
    private javax.swing.JTextField txtContraseniaUU;
    private javax.swing.JTextField txtFechaCU;
    private javax.swing.JTextField txtNombreAU;
    private javax.swing.JTextField txtNombreCU;
    private javax.swing.JTextField txtNombreCompletoAU;
    private javax.swing.JTextField txtNombreCompletoCU;
    private javax.swing.JTextField txtNombreCompletoUU;
    private javax.swing.JTextField txtNombreEU;
    private javax.swing.JTextField txtNombreUU;
    // End of variables declaration//GEN-END:variables



    
}
