/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import negocio.Administrador;
import negocio.Funcionario;
import negocio.Usuario;
import negocio.VentanaDisponible;

/**
 *
 * @author danielmej
 */
public class GUIPrincipalAdministrador extends GUIPrincipal {

    private GUIGestionUsuarios ventanaGestionUsuarios=null;
    public VentanaDisponible myUnicaVentana;
    
    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipalAdministrador(Administrador admin) {
        this.usuario=admin;
        initComponents();
        myUnicaVentana = new VentanaDisponible();
        
    }
    public GUIPrincipalAdministrador(){
        super();
        initComponents();
         myUnicaVentana = new VentanaDisponible();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskEscritorio = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuItemGestionUsuarios = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskEscritorioLayout = new javax.swing.GroupLayout(dskEscritorio);
        dskEscritorio.setLayout(dskEscritorioLayout);
        dskEscritorioLayout.setHorizontalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
        );
        dskEscritorioLayout.setVerticalGroup(
            dskEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        jMenuOpciones.setText("Opciones");

        jMenuItemGestionUsuarios.setText("Gestionar Usuarios");
        jMenuItemGestionUsuarios.setToolTipText("");
        jMenuItemGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionUsuariosActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemGestionUsuarios);

        jMenuBar.add(jMenuOpciones);

        jMenuAyuda.setText("Ayuda");
        jMenuBar.add(jMenuAyuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionUsuariosActionPerformed
        GUIGestionUsuarios ins = ventanaGestionUsuarios.GUIGestionUsuarios((Administrador) usuario,myUnicaVentana);
        try{
            if(myUnicaVentana.isNuevaVentana()){
                ins.setVisible(true);
                dskEscritorio.add(ins);
                myUnicaVentana.setNuevaVentana(false);

            }
        }catch(IllegalArgumentException e){
            System.out.println("No se puede tener mas de un ventana para la gestion de usuarios");
        }
        ins.show();
    }//GEN-LAST:event_jMenuItemGestionUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskEscritorio;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemGestionUsuarios;
    private javax.swing.JMenu jMenuOpciones;
    // End of variables declaration//GEN-END:variables

    @Override
    protected GUIPrincipal GUIPrincpal(Usuario usuario) {
        if(ventana==null){
            ventana=new GUIPrincipalAdministrador((Administrador) usuario);
        }
        return ventana;
    }
}
