/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import mvcf.AModel;
import mvcf.AView;
import negocio.Ciudad;
import negocio.Cliente;
import negocio.Funcionario;
import negocio.PaqueteComponent;
import negocio.Paquete;
import negocio.VentanaDisponible;
import negocio.Vuelo;
import recursos.MyException;
import recursos.Utilidades;

/**
 *
 * @author brayangarcia
 */
public class GUIPlanesPersonalizados extends javax.swing.JFrame implements AView {

    /**
     * Creates new form GUIPaquetesPersonalizadoss
     */
    private Paquete myPaquete;
    private Funcionario myFuncionario;
    private static GUIPlanesPersonalizados ventana;
    private static VentanaDisponible myUnicaVentana;

    public GUIPlanesPersonalizados(Funcionario myFuncionario) {
        this.myFuncionario = myFuncionario;
        myPaquete = new Paquete(9000101, "2019-07-24",'T',1);
        initComponents();
        Ciudad[] continentes=myFuncionario.consultarContinentes();

        lstRegion.setModel(new javax.swing.AbstractListModel<String>() {
        String[] nombres = devolverVectorParaLista(continentes);
        public int getSize() { return nombres.length; }
        public String getElementAt(int i) { return nombres[i]; }
        });
        Ciudad[] ciudadesOrigen=myFuncionario.consultarCiudades("America", "Colombia");
        agregarCiudadesACiudadOrigen(ciudadesOrigen);
        myPaquete.addView(this);
        System.out.println();

        
    }
    public String[] devolverVectorParaLista(Ciudad[] region){
        String []  nombres = new String[region.length] ;
        for (int i = 0; i < region.length; i++) {
            nombres[i]= region[i].getNombreCiudad();
        }
        return nombres;
    }
    
    
    public static GUIPlanesPersonalizados GUIPlanesPersonalizadosS(Funcionario myFuncionario, VentanaDisponible myUnicaVentana){
        if(myUnicaVentana.isNuevaVentana()){
            ventana=new GUIPlanesPersonalizados(myFuncionario);
            GUIPlanesPersonalizados.myUnicaVentana = myUnicaVentana;
           
        }
        return ventana;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSur = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jBtnCrearPaquete = new javax.swing.JButton();
        BtnCrearTodoIncluido = new javax.swing.JButton();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlPestaniaPaquete = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        lstRegion = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        lstCiudad = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        lstPais = new javax.swing.JList<>();
        btnVerVuelos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVerHoteles = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnVerCityTours = new javax.swing.JButton();
        txtCosto = new javax.swing.JTextField();
        BtnCarrito = new javax.swing.JButton();
        cbxOrigen = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jBtnCrearPaquete.setText("Vender Paquete");
        jBtnCrearPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearPaqueteActionPerformed(evt);
            }
        });

        BtnCrearTodoIncluido.setText("Crear Paquete Todo Incluido");
        BtnCrearTodoIncluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearTodoIncluidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSurLayout = new javax.swing.GroupLayout(pnlSur);
        pnlSur.setLayout(pnlSurLayout);
        pnlSurLayout.setHorizontalGroup(
            pnlSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSurLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(BtnCrearTodoIncluido, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnCrearPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        pnlSurLayout.setVerticalGroup(
            pnlSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSurLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnCrearPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnCrearTodoIncluido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel7.setText("Costo");

        jLabel11.setText("Region");

        jLabel12.setText("Ciudad");

        jLabel13.setText("Pais");

        lstRegion.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Caribe", "Centro América", "Europa", "Tierra Santa", "Norte de Africa", "Asia" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstRegionMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(lstRegion);

        jScrollPane9.setViewportView(lstCiudad);

        lstPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPaisMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(lstPais);

        btnVerVuelos.setText("Ver Vuelos");
        btnVerVuelos.setToolTipText("Agregar Ciudad");
        btnVerVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerVuelosActionPerformed(evt);
            }
        });

        jLabel4.setText("Para Reservar Vuelos, Click aquí: ");

        jLabel5.setText("Para Reservar Hotel, Click aquí: ");

        btnVerHoteles.setText("Ver Hoteles");
        btnVerHoteles.setToolTipText("Agregar Ciudad");
        btnVerHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHotelesActionPerformed(evt);
            }
        });

        jLabel6.setText("Para Reservar Tour turísticos, Click aquí: ");

        btnVerCityTours.setText("Ver CityTour");
        btnVerCityTours.setToolTipText("Agregar Ciudad");
        btnVerCityTours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCityToursActionPerformed(evt);
            }
        });

        BtnCarrito.setText("Ver Carrito");
        BtnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarritoActionPerformed(evt);
            }
        });

        jLabel1.setText("Ciudad de Origen");

        javax.swing.GroupLayout pnlPestaniaPaqueteLayout = new javax.swing.GroupLayout(pnlPestaniaPaquete);
        pnlPestaniaPaquete.setLayout(pnlPestaniaPaqueteLayout);
        pnlPestaniaPaqueteLayout.setHorizontalGroup(
            pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPestaniaPaqueteLayout.createSequentialGroup()
                .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPestaniaPaqueteLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(36, 36, 36)
                        .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVerHoteles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerVuelos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerCityTours, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                    .addGroup(pnlPestaniaPaqueteLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(pnlPestaniaPaqueteLayout.createSequentialGroup()
                                .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlPestaniaPaqueteLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(193, 193, 193)
                                        .addComponent(jLabel13)
                                        .addGap(194, 194, 194))
                                    .addGroup(pnlPestaniaPaqueteLayout.createSequentialGroup()
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnCarrito)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPestaniaPaqueteLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlPestaniaPaqueteLayout.setVerticalGroup(
            pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPestaniaPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPestaniaPaqueteLayout.createSequentialGroup()
                        .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPestaniaPaqueteLayout.createSequentialGroup()
                        .addComponent(cbxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPestaniaPaqueteLayout.createSequentialGroup()
                        .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BtnCarrito))
                .addGap(18, 18, 18)
                .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnVerVuelos))
                .addGap(5, 5, 5)
                .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnVerHoteles))
                .addGap(6, 6, 6)
                .addGroup(pnlPestaniaPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnVerCityTours))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Paquete", pnlPestaniaPaquete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(pnlSur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        myUnicaVentana.setNuevaVentana(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnVerCityToursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCityToursActionPerformed
        // TODO add your handling code here:

        String nombreContinente = lstRegion.getSelectedValue();
        String nombrePais = lstPais.getSelectedValue();
        String ciudadyPrecio = lstCiudad.getSelectedValue();
        String nombreCiudad = ciudadyPrecio.split("  ")[0];
        Ciudad myCiudad=myFuncionario.consultarCiudad(nombreContinente, nombrePais, nombreCiudad);

       Ciudad ciudadRepetida=(Ciudad) myPaquete.buscarCiudad(myCiudad.getIdCiudad());
        //Ya se habia registrado la ciudad en el paquete?
        if(ciudadRepetida==null){
            //Se crear la ciudad en el paquete
            myPaquete.addComponent(myCiudad);
            myPaquete.notificar();
        }else{
            //va a añadir nuevos planes en una ciudad registrada en el paquete
            myCiudad = ciudadRepetida;
        }

        String destino =nombreContinente+"-"+nombrePais+"-"+nombreCiudad;
        JDCitiyTour myGUICitiyTour = new JDCitiyTour(this, rootPaneCheckingEnabled, myFuncionario, myCiudad,myPaquete, destino);
        myGUICitiyTour.setVisible(true);
    }//GEN-LAST:event_btnVerCityToursActionPerformed

    private void btnVerHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHotelesActionPerformed

        // TODO add your handling code here:

        String nombreContinente = lstRegion.getSelectedValue();
        String nombrePais = lstPais.getSelectedValue();
        String ciudadyPrecio = lstCiudad.getSelectedValue();
        String nombreCiudad = ciudadyPrecio.split("  ")[0];
        Ciudad myCiudad=myFuncionario.consultarCiudad(nombreContinente, nombrePais, nombreCiudad);
        Ciudad ciudadRepetida=(Ciudad) myPaquete.buscarCiudad(myCiudad.getIdCiudad());
        //Ya se habia registrado la ciudad en el paquete?
        if(ciudadRepetida==null){
            //Se crear la ciudad en el paquete
            myPaquete.addComponent(myCiudad);
            myPaquete.notificar();
        }else{
            //va a añadir nuevos planes en una ciudad registrada en el paquete
            myCiudad = ciudadRepetida;
        }

        String destino =nombreContinente+"-"+nombrePais+"-"+nombreCiudad;
        JDHotel myGUIHoteles = new JDHotel(this, rootPaneCheckingEnabled, myFuncionario, myCiudad,myPaquete, destino);
        myGUIHoteles.setVisible(true);

    }//GEN-LAST:event_btnVerHotelesActionPerformed

    private void btnVerVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerVuelosActionPerformed

        String nombreContinente = lstRegion.getSelectedValue();
        String nombrePais = lstPais.getSelectedValue();
        String ciudadyPrecio = lstCiudad.getSelectedValue();
        String nombreCiudad = ciudadyPrecio.split("  ")[0];
        Ciudad myCiudad=myFuncionario.consultarCiudad(nombreContinente, nombrePais, nombreCiudad);
        
        Ciudad ciudadRepetida=(Ciudad) myPaquete.buscarCiudad(myCiudad.getIdCiudad());
        //Ya se habia registrado la ciudad en el paquete?
        if(ciudadRepetida==null){
            //Se crear la ciudad en el paquete
            myPaquete.addComponent(myCiudad);
            myPaquete.notificar();
        }else{
            //va a añadir nuevos planes en una ciudad registrada en el paquete
            myCiudad = ciudadRepetida;
        }
        
        String destino=nombreContinente+"-"+nombrePais+"-"+nombreCiudad;
        String origen = "America-Colombia-"+(String)cbxOrigen.getSelectedItem();
        JDVuelo myGUIVuelos = new JDVuelo(this, rootPaneCheckingEnabled, myFuncionario,myCiudad,myPaquete, destino,origen);
        myGUIVuelos.setVisible(true);

    }//GEN-LAST:event_btnVerVuelosActionPerformed
    public void agregarCiudadesACiudadOrigen(Ciudad[] ciudades){
        for (int i = 0; i < ciudades.length; i++) {
            cbxOrigen.addItem(ciudades[i].getNombreCiudad());
        }
    }
    private void lstPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPaisMouseClicked
        // TODO add your handling code here:
        String continente = lstRegion.getSelectedValue();
        String pais = lstPais.getSelectedValue();
        
        Ciudad[] ciudades=myFuncionario.consultarCiudades(continente,pais);
        agregarCiudadesALista(ciudades);
    }//GEN-LAST:event_lstPaisMouseClicked
    public void agregarPaisesALista(Ciudad[] paises){
        DefaultListModel modelo;
        modelo = new DefaultListModel();
        for (int i = 0; i < paises.length; i++) {
            modelo.addElement(paises[i].getNombreCiudad());
            
        }
        lstPais.setModel(modelo);
    }
    public void agregarCiudadesALista(Ciudad[] ciudades){
        DefaultListModel modelo;
        modelo = new DefaultListModel();
        for (int i = 0; i < ciudades.length; i++) {
            modelo.addElement(ciudades[i].getNombreCiudad()+"  $"+ciudades[i].getPrecioCiudadSolo());
            
        }
        lstCiudad.setModel(modelo);
    }
    private void lstRegionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstRegionMouseClicked
        // TODO add your handling code here:
        String region = lstRegion.getSelectedValue();
        
        Ciudad[] paises=myFuncionario.consultarPaises(region);
        agregarPaisesALista(paises);

    }//GEN-LAST:event_lstRegionMouseClicked

    private void jBtnCrearPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearPaqueteActionPerformed
        // TODO add your handling code here:
        Calendar fecha = new GregorianCalendar();
        //Obtenemos el valor del año, mes, día,
        //hora, minuto y segundo del sistema
        //usando el método get y el parámetro correspondiente
        int myAnio = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH)+1;
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        
        String myDia=convertirDiaoMesAHsqldb(dia);
        String myMes=convertirDiaoMesAHsqldb(mes);
        String fechaCreacion = myAnio+"-"+myMes+"-"+myDia;

        myPaquete.setFechaCreacion(fechaCreacion);
        long idPaquete=myFuncionario.asignarIdToPaquetePersonalizado();
        myPaquete.setIdPaquete(idPaquete);
        myPaquete.setTipo('P');
        myPaquete.setExistencias(0);
        myFuncionario.agregarPlanPersonalizado(myPaquete);
        Utilidades.mensajeExito("Paquete personalizado creado exitosamente", "Exito");

        JDVenderPaquete myVenta = new JDVenderPaquete(this, rootPaneCheckingEnabled,myPaquete,myFuncionario);
        myVenta.setVisible(true);
  
    }//GEN-LAST:event_jBtnCrearPaqueteActionPerformed
 private String convertirDiaoMesAHsqldb(int diaoMes) {
         String conversion=String.valueOf(diaoMes);
        if(diaoMes<10){
            conversion="0"+diaoMes;
        }
        return conversion;
 }
    private void BtnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarritoActionPerformed
        // TODO add your handling code here:
        GUICarrito myVentanaCarrito = new GUICarrito(myPaquete);
        myPaquete.addView(myVentanaCarrito);
        myVentanaCarrito.setVisible(true);
    }//GEN-LAST:event_BtnCarritoActionPerformed

    private void BtnCrearTodoIncluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearTodoIncluidoActionPerformed
        // TODO add your handling code here:
        Calendar fecha = new GregorianCalendar();
        //Obtenemos el valor del año, mes, día,
        //hora, minuto y segundo del sistema
        //usando el método get y el parámetro correspondiente
        int myAnio = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH)+1;
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        
        String myDia=convertirDiaoMesAHsqldb(dia);
        String myMes=convertirDiaoMesAHsqldb(mes);
        String fechaCreacion = myAnio+"-"+myMes+"-"+myDia;

        myPaquete.setFechaCreacion(fechaCreacion);
        long idPaquete=myFuncionario.asignarIdToPaquetePersonalizado();
        myPaquete.setIdPaquete(idPaquete);
        myPaquete.setTipo('T');
        myPaquete.setExistencias(10);
        myFuncionario.agregarPlanPersonalizado(myPaquete);
        Utilidades.mensajeExito("Paquete todo incluido creado exitosamente", "Exito");
    }//GEN-LAST:event_BtnCrearTodoIncluidoActionPerformed
    @Override
    public void actualizar(AModel amodel) {
        Paquete myPaquete= (Paquete) amodel;
        int precio=myPaquete.getPrecio();
        txtCosto.setText(""+precio);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPlanesPersonalizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPlanesPersonalizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPlanesPersonalizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPlanesPersonalizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPlanesPersonalizados(new Funcionario("Juan", "12345", "Juan Alejandro Muñoz","2019-07-02 12:32:43")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCarrito;
    private javax.swing.JButton BtnCrearTodoIncluido;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnVerCityTours;
    private javax.swing.JButton btnVerHoteles;
    private javax.swing.JButton btnVerVuelos;
    private javax.swing.JComboBox<String> cbxOrigen;
    private javax.swing.JButton jBtnCrearPaquete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList<String> lstCiudad;
    private javax.swing.JList<String> lstPais;
    private javax.swing.JList<String> lstRegion;
    private javax.swing.JPanel pnlPestaniaPaquete;
    private javax.swing.JPanel pnlSur;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtCosto;
    // End of variables declaration//GEN-END:variables




}
